/**
 * Append the condition generated by type and op to the filter.
 *
 * This uses the type's `filterCondition` method to construct
 * the condition.
 */
exports.appendFilter = function(filter, type, op) {
  var condition = type.filterCondition(op);
  if (condition) {
    if (!filter) {
      filter = condition;
    } else {
      filter += ' and ' + condition;
    }
  }
  return filter;
};
